config/routes.rb
Forum::Application.routes.draw do
  scope '(:locale)', locale: /en|fr/ do
    resources :users, only: [:create, :edit, :update, :show]
    resources :categories, only: [:index, :new, :edit, :create, :update, :destroy] do
      resources :topics
    end
    resources :topics, only: [] do
      resources :posts
    end
  end

  namespace 'api' do
    resources 'posts', only: :index
  end

  match '/(:locale)' => 'categories#index', as: :root, locale: /en|fr/
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role?(:admin)
      can :manage, :all
    end

    if user.has_role?(:user)
      can :read, Category do |category|
        !CategoryRole.category_banned_for_user?(category, user)
      end
      can :read, [Topic, Post]
      can :create, [Topic, Post]
      can :update, [Topic, Post], user_id: user.id
    end

    if user.has_role?(:guest)
      can :read, Category
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  validates :name, presence: true
  has_many :topics, dependent: :destroy
  has_many :category_roles
  has_many :users, through: :category_roles
end

app/models/category_role.rb
class CategoryRole < ActiveRecord::Base
  attr_accessible :banned, :category_id, :moderator, :user_id
  belongs_to :user
  belongs_to :category

  def self.category_banned_for_user?(category, user)
    where(user_id: user.id, banned: true, category_id: category.id).present?
  end
end

app/models/hyperlink_embedder.rb
require 'uri'

class HyperlinkEmbedder

  def initialize(url)
    @url = url
  end

  def can_process_url?
    true
  end

  def convert_to_media_markup
    "<a href=\"#{@url}\">#{@url}</a>"
  end
end

app/models/null_user.rb
class NullUser
  def username
    'Anonymous'
  end

  def has_role?(role)
    role.to_s == 'guest'
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  validates :content, presence: true
  belongs_to :topic
  belongs_to :user
  before_save :parse_content

  scope :for_activity_feed, select('posts.*, users.username AS author_name').joins(:user).order('created_at DESC').limit(5)

  private

  def parse_content
    parser = MediaEmbedder::Parser.new(content)
    self.processed_content = parser.parse_links
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection

  validates :name, presence: true
  belongs_to :category
  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username
  include Clearance::User

  has_many :posts
  has_many :topics
  has_many :category_roles
  has_many :categories, through: :category_roles
  validates :username, presence: true

  def has_role?(role)
    roles.include? role.to_s
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    posts = Post.for_activity_feed
    render json: posts
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
  before_filter :set_locale

  rescue_from CanCan::AccessDenied do |exception|
    render text: 'You are not authorized to view that page', status: 401
  end

  def current_user
    super || NullUser.new
  end

  def default_url_options(options={})
    { locale: I18n.locale }
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  authorize_resource

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find params[:id]
  end

  def create
    @category = Category.new category_params
    authorize! :create, @category
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def update
    @category = Category.find params[:id]
    if @category.update_attributes category_params
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    category = Category.find params[:id]
    category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_resource only: [:edit, :update, :destroy]
  authorize_resource

  def index
    @topic = Topic.find params[:topic_id]
    @posts = @topic.posts
  end

  def new
    @topic = Topic.find params[:topic_id]
    @post = Post.new
  end

  def edit
    @topic = Topic.find params[:topic_id]
    render layout: false
  end

  def create
    @post = current_user.posts.new post_params.merge(topic_id: params[:topic_id])
    if @post.save
      redirect_to topic_posts_path(params[:topic_id])
    else
      render :new
    end
  end

  def update
    @post.content = params[:post][:content]
    if @post.save
      redirect_to topic_posts_path(params[:topic_id])
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to topic_posts_path(params[:topic_id])
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  authorize_resource

  def index
    @category = Category.find params[:category_id]
    @topics = @category.topics
    authorize! :read, @category
  end

  def new
    @category = Category.find params[:category_id]
    authorize! :read, @category
    @topic = Topic.new
  end

  def edit
    @category = Category.find params[:category_id]
    authorize! :read, @category
    @topic = Topic.find params[:id]
  end

  def create
    @category = Category.find params[:category_id]
    authorize! :read, @category
    @topic = @category.topics.new topic_params.merge(user_id: current_user.id)
    if @topic.save
      redirect_to category_topics_path(@category)
    else
      render :new
    end
  end

  def update
    @category = Category.find params[:category_id]
    authorize! :read, @category
    @topic = Topic.find params[:id]
    if @topic.update_attributes topic_params
      redirect_to topic_posts_path(@topic)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find params[:category_id]
    authorize! :read, @category
    topic = Topic.find params[:id]
    topic.destroy
    redirect_to category_topics_path(@category)
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def create
    @user = user_from_params
    @user.roles = ['user']
    @user.username = @user.email

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render :template => 'users/new'
    end
  end

  def update
    @user = User.find params[:id]
    @user.username = valid_username_or_nil
    @user.email = params[:user][:email]
    if params[:user][:password].present?
      @user.password = params[:user][:password]
    end

    if @user.save
      redirect_to @user
    else
      flash.now[:error] = 'An error occured while saving your changes'
      render :edit
    end
  end

  private

  def valid_username_or_nil
    params[:user][:username] == "" ? nil : params[:user][:username]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def authorized_only_edit_link(path, resource, options={})
    if can? :update, resource
      link_to t('helpers.submit.update', model: resource.class.model_name.human), path, options
    end
  end

  def authorized_only_delete_link(path, resource)
    if can? :destroy, resource
      link_to 'Delete', path, method: :delete, id: "delete-#{resource.id}"
    end
  end
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/categories/edit.html.haml
%h1 Edit Category

= render 'form'

app/views/categories/index.html.haml
%h1 Apprentice IO breakable toy: Home
%p= link_to "New Category", new_category_path if can? :create, Category

%table
  %tbody
    - @categories.each do |category|
      %tr
        %td= link_to category.name, category_topics_path(category)
        %td= authorized_only_edit_link edit_category_path(category), category
        %td= authorized_only_delete_link category_path(category), category

app/views/categories/new.html.haml
%h1 New Category
= render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |type, message| %>
    <div class="flash"><%= message %></div>
  <% end %>

  <div><%= t('hello') %> <%= current_user.username %>
    <% if signed_in? %>
      <%= link_to t('profile'), current_user %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
      or <%= link_to 'Sign up', sign_up_path %>
    <% end %>
  </div>

  <%= link_to t(:log_out), sign_out_path, method: :delete if signed_in? %>
  <%= link_to image_tag('france_flag.png'), '/fr', title: 'Français' %>
  <%= link_to image_tag('uk_flag.png'), '/en', title: 'English' %>

<%= yield %>

  <% if signed_in? %>
    <div id="posts" >
    </div>
  <% end %>

  <script>Forum.pollInterval = <%= ENV['POLL_INTERVAL_IN_MS'] %></script>

</body>
</html>

app/views/posts/_form.html.haml
= form_for [@topic, @post] do |f|
  = f.label :content
  = f.text_area :content
  = f.submit

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

app/views/posts/index.html.haml
%div
  %h1= @topic.name
  = link_to 'Post Reply', new_topic_post_path(@topic)
  %div
    %h2= @topic.user.username
    %p= @topic.content

  - @posts.each do |post|
    %div
      %h2= post.user.username
      = authorized_only_edit_link(edit_topic_post_path(@topic, post), post, remote: true, class: 'edit-post')
      = authorized_only_delete_link topic_post_path(@topic, post), post
      %p= post.processed_content.html_safe

app/views/posts/new.html.haml
%h1 Post Reply

= render 'form'

app/views/topics/_form.html.haml
= form_for [@category, @topic] do |f|
  = f.label :name
  = f.text_field :name
  = f.label :content
  = f.text_area :content
  = f.submit

app/views/topics/edit.html.haml
%h1 Update Topic

= render 'form'

app/views/topics/index.html.haml
%h1= t(:topics)

= link_to t('helpers.submit.create', model: Topic.model_name.human), new_category_topic_path(@category)

%table
  %tbody
    - @topics.each do |topic|
      %tr
        %td= link_to topic.name, topic_posts_path(topic)
        %td= truncate topic.content, length: 75, separator: ' '
        %td= authorized_only_edit_link edit_category_topic_path(@category, topic), topic
        %td= authorized_only_delete_link category_topic_path(@category, topic), topic

app/views/topics/new.html.haml
%h1 New Topic

= render 'form'

app/views/users/edit.haml
%h1 Edit Profile
= form_for @user do |f|
  = f.label :username
  = f.text_field :username
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.submit 'Save'

app/views/users/show.html.haml
%h1 Profile
= link_to t('helpers.submit.update', model: t(:profile)), edit_user_path(current_user)
%ul
  %li="Username: #{@user.username}"
  %li="Email: #{@user.email}"